apiVersion: v1
kind: Service
metadata:
  name: cardano-bp
  namespace: cardano
  labels:
    app: cardano-bp
spec:
  ports:
  - name: node
    port: 3001
    targetPort: node
  - name: prometheus
    port: 12798
    targetPort: prometheus
  selector:
    app: cardano-bp

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cardano-bp
  namespace: cardano
spec:
  replicas: 1 # DO NOT CHANGE
  selector:
    matchLabels:
      app: cardano-bp
  serviceName: cardano-bp
  template:
    metadata:
      labels:
        app: cardano-bp
    spec:
      initContainers:
        - name: init-db
          image: gcr.io/cardano-slate/cardano-node:1.20.0
          command:
          - sh
          - "-c"
          - |
            echo "Creating db directory"
            mkdir -p /db/db
          volumeMounts:
          - name: db
            mountPath: "/db"
        - name: init-genesis
          image: alpine
          command:
          - sh
          - "-c"
          - |
            [ -e /genesis/mainnet-byron-genesis.json ] || wget -P /genesis https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1/mainnet-byron-genesis.json
            [ -e /genesis/mainnet-shelley-genesis.json ] || wget -P /genesis https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1/mainnet-shelley-genesis.json
          volumeMounts:
            - name: genesis
              mountPath: "/genesis"
      containers:
      - name: node
        image: gcr.io/cardano-slate/cardano-node:1.20.0
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1.5"
        command: ["cardano-node"]
        args: [
          "run",
          "--topology=/config/topology.json",
          "--database-path=/db/db",
          "--socket-path=/socket/node.socket",
          "--host-addr=0.0.0.0",
          "--port=3001",
          "--config=/config/config.json",
          "--shelley-kes-key", "/keys/kes.skey",
          "--shelley-vrf-key", "/keys/vrf.skey",
          "--shelley-operational-certificate", "/keys/node.cert"
        ]
        env:
        - name: CARDANO_NODE_SOCKET_PATH
          value: "/socket/node.socket"
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: db
          mountPath: "/db"
        - name: genesis
          mountPath: "/genesis"
        - name: socket
          mountPath: "/socket"
        - name: stake-pool-keys
          mountPath: "/keys"
        ports:
        - name: node
          containerPort: 3001
        - name: prometheus
          containerPort: 12798
      volumes:
      - name: config
        configMap:
          name: cardano-config
          items:
          - key: "config.json"
            path: "config.json"
          - key: "topology-bp.json"
            path: "topology.json"
      - name: socket
        emptyDir: {}
      - name: stake-pool-keys
        secret:
          secretName: stake-pool-keys
      # imagePullSecrets:
      #   - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: db
      namespace: cardano
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 24Gi
  - metadata:
      name: genesis
      namespace: cardano
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Mi
