apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: cardano-relay
    release: prometheus
  name: cardano-relay
  namespace: cardano
spec:
  endpoints:
  - port: prometheus
    path: /metrics
    interval: 5s
  - port: prometheus-2
    path: /metrics
    interval: 1m
  jobLabel: cardano-relay
  namespaceSelector:
    matchNames:
    - cardano
  selector:
    matchLabels:
      app: cardano-relay

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: cardano-bp
    release: prometheus
  name: cardano-bp
  namespace: cardano
spec:
  endpoints:
  - port: prometheus
    path: /metrics
    interval: 5s
  - port: prometheus-2
    path: /metrics
    interval: 1m
  jobLabel: cardano-bp
  namespaceSelector:
    matchNames:
    - cardano
  selector:
    matchLabels:
      app: cardano-bp
